print("Hii")
ans = input()
print("What is your name?")
name = input()
print("How old are you, " + name + "?")
age = int(input())
print(name, "Where are you from?")
place = input()
print("What are your hobbies, " + name + "?")
Hobbies = input()
print("Plz can you give me 5 stars for this?")
ans1 = input()
print("Thank you!!")
